security:
  user:
    password: ${USER_PASSWORD}
spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
  data:
    rest:
      base-path: /api/v1
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true